### ISSUE TITLE
Error on joining multiplayer games

### ISSUE THREAD

**Issue by hluaces** [c0dycode/Borderlands-Hex-Multitool#10]
Hey there!

A few days ago I've hexed my borderlands2 with the latest UDH version.

Ever since then, when trying to join a game with UCP enabled this error shows and the game crashes:

![Sin título](https://user-images.githubusercontent.com/3204332/55671784-d3e5cb80-5893-11e9-8f0f-aa78f5966c94.png)

I'm not sure if this is related to the hex multitool, just wondering if it might be related.

Thanks and best regards.

**Comment by c0dycode** [comment]
Hey :)
By "join a game" you mean Co-Op? If so, does it work when you play solo?

**Comment by hluaces** [comment]
It does, yes.

**Comment by c0dycode** [comment]
Okay, I'll ask around if anybody has experienced a similiar issue. If you want to try something in the meantime, you can make a backup of your exe, verify your game files via steam, hexedit again and try if that makes a difference.

Unless you have already tried that.

**Comment by hluaces** [comment]
Yeah, that was my next step. Unfortunately Steam went down right now so I can no longer continue with the testing.

I've opened the issue because I was just wondering if it was related. Probably not, on second thought, so I'll close the issue.

Thanks for your time!

Best regards.

**Comment by c0dycode** [comment]
No worries :)
Feel free to open it back up if it doesn't help. We'll keep this in our mind. This is the first report of this issue though. So it might be caused by something that gearbox changed. Patches in general seem to be quite unreliable currently.

Thanks for reaching out though :)
