### ISSUE TITLE
I have the correct file path but apply the console patch it doesn’t work. 

### ISSUE THREAD

**Issue by ShrubbyGlobe105** [c0dycode/Borderlands-Hex-Multitool#11]
Every time I open the Hex Multitool and I select BLTPS it tells me the “Console Patch is not applied”. I select Yes to apply it and nothing happens. I’ve done this a few times now

**Comment by c0dycode** [comment]
Sorry for the delay. Been sick lately, so I had to take a little break :)

If you use version 1.25 then it's most likely an Antivirus software interfering.
