### ISSUE TITLE
Can't assign a label for "Console and Set Command" + Lots of errors

### ISSUE THREAD

**Issue by DrChaz1385** [c0dycode/Borderlands-Hex-Multitool#12]
I don't even know.
https://youtu.be/SgtSkKC0yvQ

**Comment by c0dycode** [comment]
Verify your files via steam and disable any antivirus temporarily.
Then try again. This is very unlikely an issue with the Multitool itself, but rather something external interfering with it.

**Comment by DrChaz1385** [comment]
The Borderlands 2 validation was the issue (2 files).
Thank you SOOO much for the 10/10 customer service quality. I wish others were like this XD

**Comment by c0dycode** [comment]
Glad you got it working :)

Also, one of those files will always be the exe. Since the new UHD-update there is a second file that it can't verify, for some reason. I don't think anybody has looked into which one it is though.
