### ISSUE TITLE
Hexedit error and deleting my executable 

### ISSUE THREAD

**Issue by lenzoo0100** [c0dycode/Borderlands-Hex-Multitool#14]
Hi im having a major issue with hex. It works find but as soon as i select the path and apply mt changes it gives me this error https://imgur.com/a/eRMIN15 i have reinstalled everything multiple times i can't find why its giving me this issue. After this error pops up it seems to delete my executable and i have to restore from my backup.

**Comment by c0dycode** [comment]
The error message is a little misleading and I can't seem to find too much information about it, besides that most likely any antivirus software is interfering with it.

Since a few antivirus tools delete the games exe after/during hexediting, this sounds very similiar.
