### ISSUE TITLE
Cannot check the checkboxes for sanity checks or console key.

### ISSUE THREAD

**Issue by Ulysses8** [c0dycode/Borderlands-Hex-Multitool#15]
Trying to install the Reborn mod and using the tutorial found here: https://github.com/kallivee/Hex-Guide/wiki. For some reason though, while using the multi tool, I can't mark any checkboxes. Can't figure out how to solve this, feels like user error on my part but I'm at a loss.

**Comment by c0dycode** [comment]
If you're using a custom theme for windows, that's most likely the issue.
With a custom theme, the checkmark will be set, but due to the theme not visible.

**Comment by Ulysses8** [comment]
Damn dude you rock. Had no idea custom themes could cause problems like that, Thanks!
