### ISSUE TITLE
Multitool Not Opening

### ISSUE THREAD

**Issue by scottwilson0308** [c0dycode/Borderlands-Hex-Multitool#16]
Hey c0dy,

First off, thank you for all your hard work. This community would be at a loss without you.

I've used your Multitool with BL2. Now starting up BLTPS for the first time. I've read through #9 and so I downloaded the newest 1.25, which doesn't seem to work at all for me. I've tried extracting to the master folder, extracting elsewhere, not extracting, etc. As far as I can tell, I've done everything right (including .NET Framework 4.5+), but for the first time, the Multitool won't even open. Tried with Local AppData folder full, empty and deleted for both the Multitool and BLCMM. I'm at a total loss. Any suggestion would be great!

Again, thank you for all the great work you've done for our community!

**Comment by scottwilson0308** [comment]
Ever wish you could remove a posted

**Comment by scottwilson0308** [comment]
issue, because it was your computer being an ***hole that caused the problem in the first place? For some reason, it was happy to open the older version. Needed a restart before it would be a good bot and open 1.25 -_-

**Comment by c0dycode** [comment]
Interesting issue. Glad you got it fixed though :)
Enjoy ❤️
