### ISSUE TITLE
Help, i am stupid

### ISSUE THREAD

**Issue by dementedwhale45** [c0dycode/Borderlands-Hex-Multitool#17]
Hello, i have a problem, so the BL Hex Multitool seems like its installed (https://imgur.com/HMphOpn), but then after i revert it this happens (https://imgur.com/K5Pe8V2), and when i open the BL Hex MT from BLCMM, it appears to have an older version (version 1.18) when i have downloaded the newest version (1.25) and after i press apply a message appears ¨Borderlands Hex Multitool stopped working¨ (https://imgur.com/q0JDFmH), every time i open BL2 and execute BL2Reborn.txt and start playing, Borderlands stops working after a few seconds (probably because the sanity check wasn't patched), i need help.
Ps. Sorry that the console messages are on spanish

**Comment by c0dycode** [comment]
You need to verify your game files via steam.
After that, do not attempt to hexedit via BLCMM or the 1.18 Multitool.

You need to launch the 1.25 Multitool manually, not via BLCMM. Then it should work fine

**Comment by dementedwhale45** [comment]
So, i even uninstalled and downloaded BL2 it back, put everything back together, it does execute on the main menu but once i start playing, it crashes, i haven't launched the Multitool via BLCMM once, only manually, i did verify the files, it still doesn't work

**Comment by c0dycode** [comment]
If the Patch/Reborn executes fine, then the Multitool did its job. If the game crashes afterwards, then your best bet is asking on the Reborn Discord server, since they're more familiar with those issues than me.

> when i have downloaded the newest version (1.25) and after i press apply a message appears ¨Borderlands Hex Multitool stopped working¨ 

In the linked screenshot with that message, you're using version 1.18, which won't work.

And should the Sanity Check not be patched, that wouldn't result in the game crashing. That'd only lead to your items/weapons being deleted.

**Comment by Deafpycoder** [comment]
Hey, I've tried doing the same thing, I've got dementedwhale45's problem. However, how do I find the 1.25 multitool? I googled it and it's not showing anywhere?

**Comment by c0dycode** [comment]
It's either on Nexusmods or right here in this repo.
[BL Hex-Multitool .NET 4.5.zip](https://github.com/c0dycode/Borderlands-Hex-Multitool/blob/master/BL%20Hex-Multitool%20.NET%204.5.zip)

**Comment by Deafpycoder** [comment]
Your repo doesn't seem to have BLCMM included. Just downloaded it now and when I opened it, it redirected to my text editor.

**Comment by c0dycode** [comment]
Why would it include BLCMM? 🤔 It's a completely separate tool.
If you download it, you simply need to extract it with 7-Zip, WinRAR or Windows itself and then launch the application.

**Comment by Deafpycoder** [comment]
Wait, this is for Windows only? Thought it was meant for both Windows and Mac.

**Comment by c0dycode** [comment]
Correct, the Multitool is only for Windows.
