### ISSUE TITLE
1.5? Not really

### ISSUE THREAD

**Issue by BlazeStryker** [c0dycode/Borderlands-Hex-Multitool#18]
I keep trying to download your so-called version 1.5 as pictured but it's 1.25 and I'm frankly a bit annoyed.

**Comment by c0dycode** [comment]
There is no version 1.5.
You're probably mixing it up with the .NET 4.5, which is the framework that I used to program this tool and that is a requirement to also use it. It should be installed by windows updates these days though.

1.25 is currently the latest version.
