### ISSUE TITLE
Crash because Borderlands 2 has update

### ISSUE THREAD

**Issue by lyuha** [c0dycode/Borderlands-Hex-Multitool#19]
Today, Borderlands 2 has update for DLC.
hex multitool needs to update.

**Comment by c0dycode** [comment]
Already working on an update :)

**Comment by lyuha** [comment]
Thanks!

**Comment by c0dycode** [comment]
[BL Hex-Multitool .NET 4.5.zip](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/3270295/BL.Hex-Multitool.NET.4.5.zip)
Give version 1.26 a try :)

it appears to be working fine so far for me.  Let me know if you have any issues 👍

**Comment by Buzing** [comment]
Just chiming in to say it works great for me~!

**Comment by c0dycode** [comment]
Awesome! :)

**Comment by lyuha** [comment]
It works! Thanks! 👍
