### ISSUE TITLE
New version 1.26 does not work for new dlc / can not type in input key for console

### ISSUE THREAD

**Issue by bschurman1** [c0dycode/Borderlands-Hex-Multitool#20]
I get spammed with a whole bunch of popups of errors when trying to patch post-lilith dlc. I am updated to 1.26

**Comment by bschurman1** [comment]
i miss my modded guns lol

**Comment by Buzing** [comment]
works great for me. can you give us a picture of the errors you receive ? 

relinking for visibility
https://github.com/c0dycode/Borderlands-Hex-Multitool/files/3270295/BL.Hex-Multitool.NET.4.5.zip

**Comment by bschurman1** [comment]
funny story, i hopped on my pc to take the pictures and... it works now?! I guess its all okay lol
