### ISSUE TITLE
Borderlands 2 exe does not show

### ISSUE THREAD

**Issue by theyellingmute** [c0dycode/Borderlands-Hex-Multitool#23]
the exe file will not shot up at all in the multitool, it is in the win32 folder like always and launches just fine.

heres it trying to setup borderlands 2 https://imgur.com/a/D1HAtRG

and here it is having no issue finding pre sequel https://imgur.com/a/oApilrG

ive verified the game cache and even gone as far as to reinstall the game and still nothing.

**Comment by c0dycode** [comment]
Look at the bottom right and then at the addressbar at the top.

You pressed the BL2 Filepath Button, it filters for the Borderlands2.exe (bottom right) but you are in the TPS folder.

**Comment by theyellingmute** [comment]
wow im dumb, i guess i just assumed if it was in the win32 it would automatically go to that games file
