### ISSUE TITLE
Max Level

### ISSUE THREAD

**Issue by OrionValentine** [c0dycode/Borderlands-Hex-Multitool#24]
G'day, first time using this tool. Normally I just use BLCMM and let that do all the work. Anyways, I set the max level to 80 through the tool, yet I'm still gaining experience beyond level 80, and I really don't want that. Any ideas on how to fix this so I can keep playing my characters without worrying about leveling beyond 80?

**Comment by c0dycode** [comment]
That issue comes up if you hexedited with an outdated version. Your best bet is to verify your files via steam, hexedit with 
 version 1.27 and you'd need to set your characters level to 80 with Gibbed :)

**Comment by OrionValentine** [comment]
How do I use Gibbed? I'm practically computer illiterate.

**Comment by c0dycode** [comment]
You got it working now? :)
