### ISSUE TITLE
"BorderlandsHexMultitool.exe has stopped working"

### ISSUE THREAD

**Issue by Kumomaku** [c0dycode/Borderlands-Hex-Multitool#25]
I'm simply trying to launch my hex multitool but it seems that it doesn't even launch when I try to run it. I tried running it as admin. tried putting it in the binaries folder and running it as admin again, still didn't work even though I'm aware it doesn't need to be in a specific place.

Here's a picture when I try to run my Hex Multitool
![Hex](https://user-images.githubusercontent.com/51953032/59675033-03e80e00-91f7-11e9-98b5-ee3807f433dc.JPG)

**Comment by c0dycode** [comment]
Make sure you have .NET 4.5 or higher installed.
If you do, then I'd need to see the error, if you click on "View Problem Details".

**Comment by Kumomaku** [comment]
> Make sure you have .NET 4.5 or higher installed.
> If you do, then I'd need to see the error, if you click on "View Problem Details".

Sorry I took a while to reply. Yes I do have .Net 4.5 installed, here's the problem details.
![hex1](https://user-images.githubusercontent.com/51953032/60341583-918ae100-99e1-11e9-9ff9-b128be299c61.JPG)
![hex2](https://user-images.githubusercontent.com/51953032/60341584-918ae100-99e1-11e9-869e-3e7371fa8933.JPG)
![hex3](https://user-images.githubusercontent.com/51953032/60341587-92bc0e00-99e1-11e9-9d70-0696dfb9e9f6.JPG)

**Comment by c0dycode** [comment]
Hm, I've tried to remove all C++ Redist. from my Win 7 VM plus all .NET Frameworks and it still either runs fine or I get a proper message, telling me I should install .NET Framework x.y!

The way I packaged the Multitool is that required DLLs are being "weaved" into the exe. So that there are less files in the folder. It then tries to load these DLLs from within the exe at Runtime.

Maybe something like your Antivirus is blocking this step and therefore you get that message? Otherwise I'm not really sure how to approach this issue, since there's no clear error and I can not reproduce this issue.

**Comment by Kumomaku** [comment]
> Hm, I've tried to remove all C++ Redist. from my Win 7 VM plus all .NET Frameworks and it still either runs fine or I get a proper message, telling me I should install .NET Framework x.y!
> 
> The way I packaged the Multitool is that required DLLs are being "weaved" into the exe. So that there are less files in the folder. It then tries to load these DLLs from within the exe at Runtime.
> 
> Maybe something like your Antivirus is blocking this step and therefore you get that message? Otherwise I'm not really sure how to approach this issue, since there's no clear error and I can not reproduce this issue.

Ok thanks for the reply, This problem also happens when I try to open Borderlands 2 so maybe that's the problem. I appreciate the help regardless

**Comment by Amaroq-Clearwater** [comment]
I'd suggest using the .NET Core instead of the normal .NET framework. Completely portable, and completely cross-platform. No DLLs needed, hopefully.

**Comment by c0dycode** [comment]
That'd make the library, which handles all the functionality, cross platform, but not the GUI.
I already have a C++ version in development though, which already works on both Windows and Linux.
