### ISSUE TITLE
Disable Logitech Stuff?

### ISSUE THREAD

**Issue by WubTheGame** [c0dycode/Borderlands-Hex-Multitool#27]
What does this do? I have a logitech mouse, so...

I'd ask on the Discord, but I've temporarily lost access to my account due to a stupid error on their side.

**Comment by c0dycode** [comment]
That actually wasn't supposed to be there, but I might aswell leave it in there.
It's simply trying to disable the loading of some Logitech related dll which causes a Keyboards lighting to do some funky stuff. Nothing if any real interest.

**Comment by WubTheGame** [comment]
Oh, cool.
Okay then.
