### ISSUE TITLE
not sure if im just dumb or....

### ISSUE THREAD

**Issue by itsalchemist** [c0dycode/Borderlands-Hex-Multitool#3]
ive checked multiple tutorials and from what they say everything should be working but nothing on my actual game has changed

**Comment by c0dycode** [comment]
Which changes did you apply?
The only changes that'll be "instantly" visible, would be the Backpack/Bank-changes if you either
a) Have purchased all Backpack/Bank-SDUs
b) Changed the Spacetrigger to your current Backpack/Bank-space.

Also, do the values show up the way you changed them to, if you relaunch the Tool/click one of the icons again to "reload" the file?
