### ISSUE TITLE
Sanity check bypass doesn't work joining matches

### ISSUE THREAD

**Issue by atmogenic** [c0dycode/Borderlands-Hex-Multitool#31]
Seems that the bypass doesn't work when joining other people, it worked when i created a weapon and class mod for a test and it was sucessful when i started my own game, but when i searched for other people, my weapon disappered but not my class mod. I had the gun equiped in my own game but not the class mod. I then loaded up a lower level character as being high level usually ends with no matches found. Once i was in a match, i selected my high level character and once i got in, my weapon was gone when i had it in my equip slot, but like i said my class mod was still there but i didn't equiped it.

I don't know if this is because of me loading different characters or that going into people's matches disables the patch for the sanity checks.

**Comment by MagicGonads** [comment]
Sanity check bypass works on your inventory not on what you have equipped.
When you join other players technically your equipment is part of their inventory not yours.

Same reason why if you mess with the loot balances too much you can end up deleting weapons from your guests' inventories.
