### ISSUE TITLE
Hex-Edit makes "The Dust"-Region inaccessible due to game Crash

### ISSUE THREAD

**Issue by PhilippHtz** [c0dycode/Borderlands-Hex-Multitool#33]
I'm having a wierd issue with the patch. Installing it and enabling the console isn't a problem... The patch works and everything is fine. That is until I try to enter "The Dust". Whenever I go there the loading-screen just starts to freeze for a few moments and then a message pops up saying: Fatal Error: Adress = 0x0 (filename not found). Again, everything works just fine except that I can't enter "The Dust" and I simply don't know what the issue is. I've searched for an answer for hours but couldn't find any threads where this error-message was shown. I tried un- and reintsalling the game, manually hex-editing my Borderlands2.exe, deleting the Borderlands2 Folder in "My Games"and nothing works. It is also worth noting that this problem only occurs after I enable the console/ hex-edit the game. Before I do that I can go to "The Dust" without any problem. Also, if I repair the game via Steam it says that 2 files have been restored...
Pls help me because I am at a loss as to what I should do

**Comment by c0dycode** [comment]
The only "solution" I've heard of with that error is described [here](https://bl2reborn.fandom.com/wiki/Troubleshooting_BL2_Reborn) on the BL2 Reborn wiki.

Other than that, I'm not aware of anything else you could try. Besides the usual stuff, like - disabling antivirus software temporarily when you hexedit the games exe.
