### ISSUE TITLE
Multitool doesn,t work again.

### ISSUE THREAD

**Issue by zer00s** [c0dycode/Borderlands-Hex-Multitool#34]
It seems like gearbox released a fix to the new patch, beacouse multitool doesn't work again.
I would appreciate fixing it.

**Comment by c0dycode** [comment]
Should be fixed with the version I just uploaded :)

**Comment by zer00s** [comment]
Thanks for quick fix.👍

pon., 2 mar 2020, 20:42 użytkownik c0dycode <notifications@github.com>
napisał:
