### ISSUE TITLE
Console Patch is Incomplete

### ISSUE THREAD

**Issue by Syphist** [c0dycode/Borderlands-Hex-Multitool#35]
The game was just updated today and the console patch is incomplete. "83C40C85C0751A6A" is successfully converted to "83C40C85FF751A6A" but when you type "exec patch.txt" into the console it outputs "say exec patch.txt". I was successfully able to patch it manually, however I forget the address the unicode "say" string was located at.

**Comment by c0dycode** [comment]
Did you use version 1.32?

**Comment by Syphist** [comment]
I must've submitted this bug report right before you updated it or didn't properly see it. Thanks for pointing that out.
