### ISSUE TITLE
deletes executable after restart

### ISSUE THREAD

**Issue by MongLee2** [c0dycode/Borderlands-Hex-Multitool#36]
The hex editor works perfectly fine and I don't have issues with playing the game, However, when I shut down my computer for the night and return the next day my my executable for borderlands 2 isn't in the folder. Forcing me to verify the game files and launch again. the game works fine after verifying and even is still hex edited.

**Comment by c0dycode** [comment]
Sounds like something an antivirus software might do.
Try whitelisting your BL2 folder in your antivirus software. Or at least the exe itself.

**Comment by MongLee2** [comment]
Thanks for the assistance, if you don't hear from me it worked. The antivirus completely escaped my mind as something to do that.
