### ISSUE TITLE
Can't exec Patch.txt when Steam is set to offline mode 

### ISSUE THREAD

**Issue by 60n3z** [c0dycode/Borderlands-Hex-Multitool#37]
The game crashes and is giving a series of "address not found" errors when I try to execute UCP when Steam is set to offline mode. UCP works well when online.

**Comment by c0dycode** [comment]
That's because gearbox messed up yet again. If you're offline/not connected to shift and you try to use the chat, your game will crash.

All you should ™️ have to do is, remove the "say " line from the patch with BLCMM.

**Comment by 60n3z** [comment]
Worked like a charm. Thank you! So to clarify, it's Gearbox's fault, not the Hex-Multitool?

**Comment by c0dycode** [comment]
Correct. We can only speculate, but it most likely is a result of them changing their chat-system to be compatible with cross-play (steam, epic) or something along those lines.
