### ISSUE TITLE
Console Commands

### ISSUE THREAD

**Issue by Kuriboh1612** [c0dycode/Borderlands-Hex-Multitool#4]
I'm having an issue that when I use the Console Commands, it does not add levels or put me in third person. It only shows it on the chat log. What am I doing wrong?

**Comment by c0dycode** [comment]
If it's saying it in the chat, make sure this option is checked.
![image](https://user-images.githubusercontent.com/3851319/38211013-61e9a648-36b9-11e8-9a50-36873b43d94a.png)

That should make commands like exec, obj dump, getall work just fine. Other commands like adding levels, are Developer Commands, iirc, which would require different hexediting, which this tool does not provide.

**Comment by nkey4432** [comment]
I’m having an issue where it not showing any options for the command keys... like I can hit the drop down arrow but it’s just blank. I tried customizing it but it just crashes instead

**Comment by c0dycode** [comment]
That's due to the update from today and should be fixed with the next update for the Multitool. #9
