### ISSUE TITLE
Borderlands TPS crashes after using Hex-Multitool

### ISSUE THREAD

**Issue by RobertVorback** [c0dycode/Borderlands-Hex-Multitool#40]
Using version 1.33 of the tool for Borderlands TPS
When starting the game it crashes with an error message which has a very long list of errors about file not found etc. After verifying the game files again the game will start ok. I will attach the crash dump file if it is any use for trouble shooting.
[borderlandspresequel_2140713_crash_2020_4_10T2_47_46C0.zip](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/4459726/borderlandspresequel_2140713_crash_2020_4_10T2_47_46C0.zip)

**Comment by c0dycode** [comment]
Have you used CommandInjector and&or autoexec by me before? If so, make sure autoexec is removed and CommandInjector is updated.

If not, then this usually happens if your antivirus software is interfering with the hexedit. In that case you either need to whitelist the TPS exe or the whole folder.

**Comment by RobertVorback** [comment]
Yes I have used CommandInjector and autoexec before but
don't have either installed now,. Your advice to whitelist the
TPS folder did the trick. Hexedit applied, game works with or without the patch, and now I know why I was getting crashes after using Gibbed, same deal with Windows defender.
Issue solved.
Thank you c0dycode

**Comment by c0dycode** [comment]
Awesome :)
Enjoy!
