### ISSUE TITLE
Can't get past title screen

### ISSUE THREAD

**Issue by CrazyChris576** [c0dycode/Borderlands-Hex-Multitool#44]
I have downloaded Hex Multi-Tool, assigned my file paths, and made literally only one change of disabling the BL3 ads. I left every other value as is in the Hex. I open up my game and try to load a save file, it gets to the blue digispawn animation and immediately freezes, and then my game crashes. I haven't even tried to run any mods. This is just hex edit and load, and then it immediately crashes. Help please.

**Comment by c0dycode** [comment]
Which Platform are you on? Steam or Epic?

I tested on steam and it works fine.
I'd suspect that you're using a third-party antivirus that messes up the hexedit.
A well known offender of this is Avast.

So verify your files via steam/epic, disable your antivirus and try again.

**Comment by CrazyChris576** [comment]
I'm on Steam. The only antivirus I run is Windows Defender. No third-party here.

**Comment by c0dycode** [comment]
Make sure that one also doesn't interfere. I can only assume that this is not related to the Multitool itself, since it's been working fine for a lot of people.

Your best bet either way is to:
* Delete Borderlands2.exe
* Verify game files via steam
* Disable Antivirus
and then try again.
