### ISSUE TITLE
运行程序报数组越界，游戏路径为全英文且无空格。报错全信息为：IndexOutOfRangeException during scan for address!索引超出了数组界限

### ISSUE THREAD

**Issue by Songnis** [c0dycode/Borderlands-Hex-Multitool#46]

**Comment by Default-Devv** [comment]
Not to backseat moderate, but english please, much easier to help if it's
understandable, I dont know Japanese unfortunately at the moment

**Comment by c0dycode** [comment]
As Default-Devv said, it would make things a little easier if you could try to use english instead.
Google translator or similar are sufficient aswell, if you're not comfortable enough.

However, the most common issue people run/ran into is that their antivirus is interfering with the Multitool.
This would be my first suggestion: To temporarily disable the antivirus and see if that helps.

**Comment by Songnis** [comment]
I am so sorry that it will be better if I described the error in English. I just want to tell you an error occured when I ran the Multitool.
It said "IndexOutOfRangeException during scan for address! The index exceeds the bounds of the array". I also want to say that my computer does not have any antivirus software

**Comment by c0dycode** [comment]
Make sure that Windows Defender is also not interfering.
Apart from that, I don't really know what else causes this. In the past people that had this issue told me that they just tried a couple more times and at some point it just worked.

If you have access to a second system (another computer/laptop) you could transfer your Borderlands exe onto that and try the Multitool there instead.

**Comment by Songnis** [comment]
@c0dycode 
The problem remains

**Comment by c0dycode** [comment]
Okay, in that case my last suggestion still stands.
If you have access to another system, try to use that instead.

If using another system is not an option for you, you'd need to be a little more patient as I'm currently working on an alternative. But that might take a couple more days.

**Comment by c0dycode** [comment]
https://c0dycode.github.io/Borderlands-Hex-Multitool/

See if this works for you instead :)
