### ISSUE TITLE
whenever I use hex editor it says catastrophic error when I select a path

### ISSUE THREAD

**Issue by demonicshrek** [c0dycode/Borderlands-Hex-Multitool#47]
could u fix this please I'm on windows 10 btw

**Comment by c0dycode** [comment]
There's nothing to fix there for me.
You're trying to open a Borderlands shortcut, not the exe directly.

You need to open the exe.
Which is located in "C:\Program Files (x86)\Steam\steamapps\common\Borderlands 2\Binaries\Win32\Borderlands 2.exe", for example.
