### ISSUE TITLE
virus in multitool

### ISSUE THREAD

**Issue by rozzzzz** [c0dycode/Borderlands-Hex-Multitool#49]
so i just got borderlands for pc and i wanted the patch and downloaded the multitool and windows is saying its a virus and its a trojan

**Comment by c0dycode** [comment]
It's a false positive.
If you'd like to be 100% safe, you even could copy the Multitool and the Borderlands exe onto a pc that has no internet connection and it'd work fine.

You could also try and use the webversion instead (this cannot set your ConsoleKey though).
https://c0dycode.github.io/Borderlands-Hex-Multitool/

This should be even safer to use.
Happy holidays :)
