### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by BaileeTGG** [c0dycode/Borderlands-Hex-Multitool#5]
When I tried to Download the file Windows Defender Antivirus Detected a severe trojan in the download. Is this just Windows being dumb or should I try to get the download off of a friend?

**Comment by BaileeTGG** [comment]
Oh I forgot to add the name of the trojan file is Trojan:Win32/Fuerboos.C!cl

**Comment by c0dycode** [comment]
Somebody has reported something similiar with Windows Defender before.
I've submitted the file to MS so they can check it.

![image](https://user-images.githubusercontent.com/3851319/38328000-feda0e98-3849-11e8-98e4-ffcbaad2e728.png)

Doesn't seem to have been "whitelisted" or anything though. So, not sure what else I could do about it.

Here's a scan via. Virustotal though.
https://www.virustotal.com/#/file/4069d9b1df62cada9d292501a9b744e1258c081b1d71f9589caad602cdb94ba7/detection

**Comment by BaileeTGG** [comment]
k I will just continue the download and let windows bypass the "virus" to say thx for the help
