### ISSUE TITLE
Trying to open the tool

### ISSUE THREAD

**Issue by 76656** [c0dycode/Borderlands-Hex-Multitool#54]
When i try to open the tool it says failed to save settings: Unable to save confing to file 
"c/users/-/Appdata/local/BorderlandsHexMultiTool/BorderlandsHexMultiTool.e_jjrmxzxyo1fsmpkrrzchm5gqvdq33huj/1.38.0.0/user.config"
I have used the tool before but i wanted to use bl2 reborn and i have to turnoff sanity checks to use it
![image_2021-06-04_192606](https://user-images.githubusercontent.com/85374479/120871797-b5121b00-c56a-11eb-9757-97e1ecd5c9f4.png)
i have the game on my d drive if that matters

**Comment by c0dycode** [comment]
The only issue related to the config-file I've seen so far, was that the selected file path(s) did not save.

Try this one from the readme:

Q: My Paths are not saving, what should I do?

A: Go to "%localappdata%\BorderlandsHexMultitool" and delete the subfolders, then try again! If that also doesn't solve your problem, try running the tool as administrator. Should that also not work, please contact me!

**Comment by 76656** [comment]
TY that worked.
