### ISSUE TITLE
Big one: There's bnothing really here.

### ISSUE THREAD

**Issue by Gaalidas** [c0dycode/Borderlands-Hex-Multitool#7]
You've got a repository with information about a program... but no program!  This is a huge issue that should really be looked into.  What's the point of a repository to house a screenshot, a readme, and a .NET runtime package?  It's pointless, that's what it is!

**Comment by c0dycode** [comment]
Not sure what else to tell you, other than "BL Hex-Multitool .NET 4.5.zip" contains the program. 🤔

**Comment by y0LAs** [comment]
Well, I'm also a little confuse to see that there is nothing here :
https://github.com/c0dycode/Borderlands-Hex-Multitool/releases
But I find this website absolutely unintuitive, my brain can't adapt to the way of thinking it has been made with.
Seriously, I don't know how to download stuff other than manually typing /releases at the end of the main project url...
And I do computer support for a living xD
