### ISSUE TITLE
Problem with the UVHM level editor

### ISSUE THREAD

**Issue by Megamech7** [c0dycode/Borderlands-Hex-Multitool#8]
The level editor on BL2 works fine and i used it many times but i tried to make a custom patch for TPS so i could play UVHM at level 1 but it didnt seem to work. I tried copying the one in the readme or just copying the BL2 one and just changing the game but nothing seemed to work. It seems to work when i first press TPS the option shows while it is loading the patches but it dissapears when the loading ends. I posted the same on the borderlands subreddit but i think this is a better place to post it.

**Comment by c0dycode** [comment]
Yeah, just changing the game won't work and can be dangerous even, if the bytes of the Patchsignature do exist in the TPS exe but do something completely different. 

It'll disappear if the "Patchsignature" is not found.

[UVHM Level Modifier TPS.txt](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/2776657/UVHM.Level.Modifier.TPS.txt)

This should do the job though :)

**Comment by Megamech7** [comment]
ok thanks this works

**Comment by Megamech7** [comment]
since the new update that broke all mods and the tool, the old uvhm modifier doesnt work with the new version of tool. I saw that there is a updated version of the level editor for bl2 in there and i would be evry happy if you could make one for tps again

**Comment by c0dycode** [comment]
Apologies, I once again totally forgot about this.

[UVHM Level Modifier TPS UHD.txt](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/3059053/UVHM.Level.Modifier.TPS.UHD.txt)

I'll include them both in the next update. Until then, you can just put the attached file in there :)
No need to replace the old one, they can both be there
Let me know if it works :)

**Comment by Megamech7** [comment]
Thank you so much for replying so fast. It works
